### PR TITLE
Few important changes for Bungeecord option

### PR DESCRIPTION
**Pull request by Yggdrasil80**
For the messages_fr file, i review all traductions because they are not at all accuracy

Edits in Main and in MySqlSupport files to just dont close connection, and continue to sync with database

Few edits in PlayerJoinQuit Listener, to sync files in database when player changing server, and load data 10 seconds later when player connects to another server. With this system the plugin dont load the old skills data, before the save
Its very useful on bungeecord and dont need to spam saves in database, save delay can be 60 without any sync problem

### CODE REVIEW

**Comment by Archy-X** [comment]
Btw this isn't going to get merged because it's already working in the beta branch and coming soon

**Comment by Yggdrasil80** [comment]
Ok but can you merge the FR trads please, the actuals trads are not at all french x)

**Comment by Archy-X** [comment]
Could you do that on Crowdin please? https://www.crowdin.com/project/AureliumSkills

**Comment by Archy-X** [comment]
And make sure you keep the original colors found in the English version, not any colors or styles you changed

**Comment by Yggdrasil80** [comment]
Sure i will do that this week

**Pull request closed without merging**
