### PR TITLE
Updated pom.xml with the latest dependency releases

### PR DESCRIPTION
**Pull request by zhro**
Updated pom.xml with the latest dependency releases, checked against all accessible Maven repositories.

### CODE REVIEW

**Comment by Archy-X** [comment]
Getting a compilation error with WorldGuard:
```
cannot access com.sk89q.worldguard.bukkit.WorldGuardPlugin
  bad class file: C:\Users\andre\.m2\repository\com\sk89q\worldguard\worldguard-bukkit\7.0.7\worldguard-bukkit-7.0.7.jar(com/sk89q/worldguard/bukkit/WorldGuardPlugin.class)
    class file has wrong version 60.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by Archy-X** [comment]
I don't want to update above Java 8 right now since it would break support for MC versions below 1.17.

At some point I will update to Java 17 and drop support for older versions but not in the foreseeable future.

**Comment by zhro** [comment]
This means that WorldGuard 7.07 is using Java 16. I'll validate this for you back to 1.8 and set a new commit.

**Comment by zhro** [comment]
I've reverted WorldGuard to version 7.0.5 and confirmed that it builds successfully with Java 1.8. This is the last version for 1.8, and is slightly newer than the one configured previously in the pom.

I noticed that you updated the ProtocolLib version to a more recent commit; I wasn't able to build with the old pom, and had switched this dependency out for the latest 5.0.0 snapshot from their maven repository. Would you prefer to build against the Git repo?

**Comment by Archy-X** [comment]
Until ProtocolLib officially releases 5.0.0 then yes I would like to build using Jitpack and the latest commit number.

**Comment by zhro** [comment]
Reverted the ProtocolLib dependency, as requested. The only other issue I see is that you targeted Spigot-API 1.19 (I updated it to 1.19.2), but this has the risk of hiding possible compatibility errors, if you add feature that doesn't exist in the older versions that you want to support.

**Pull request merged**
